apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://ysdevn_db_user:devquiz%40123@ac-mtcrqdv-shard-00-00.vrd0v5v.mongodb.net:27017,ac-mtcrqdv-shard-00-01.vrd0v5v.mongodb.net:27017,ac-mtcrqdv-shard-00-02.vrd0v5v.mongodb.net:27017/DQuiz?ssl=true&replicaSet=atlas-dm4r3q-shard-0&authSource=admin&retryWrites=true&w=majority"
  PORT: "5000"
  JWT_SECRET: "superstrongsecretkey123"
  BACKEND_PORT: "3000"
  FRONTEND_PORT: "8080"
  NODE_ENV: "production"
