apiVersion: v1
kind: Service
metadata:
  name: dquiz-backend-service
  namespace: dquiz
spec:
  type: ClusterIP
  selector:
    app: dquiz-backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
