apiVersion: apps/v1
kind: Deployment
metadata:
  name: dquiz-backend
  namespace: dquiz
  labels:
    app: dquiz-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dquiz-backend
  template:
    metadata:
      labels:
        app: dquiz-backend
    spec:
      containers:
        - name: dquiz-backend
          image: deviliam/dquiz-backend-1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-secret
