apiVersion: apps/v1
kind: Deployment
metadata:
  name: dquiz-backend
  labels:
    app: dquiz-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dquiz-backend
  template:
    metadata:
      labels:
        app: dquiz-backend
    spec:
      containers:
        - name: dquiz-backend
          image: deviliam/dquiz-backend-1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://ysdevn_db_user:devquiz%40123@cluster0.vrd0v5v.mongodb.net/DQuiz"

            - name: PORT
              value: "5000"

            - name: JWT_SECRET
              value: "superstrongsecretkey123"
