apiVersion: v1
kind: Service
metadata:
  name: dquiz-backend-service
  labels:
    app: dquiz-backend
spec:
  selector:
    app: dquiz-backend
  ports:
    - name: http
      port: 5000        # Cluster-wide port
      targetPort: 5000  # containerPort inside pod
  type: ClusterIP
