apiVersion: v1
kind: Service
metadata:
  name: dquiz-frontend-service
  namespace: dquiz
spec:
  type: ClusterIP
  selector:
    app: dquiz-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
