apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dquiz-ingress
  namespace: dquiz
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: "54.186.112.111.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dquiz-frontend-service
                port:
                  number: 3000
