name: DQuiz CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:

  build-backend:
    name: Build & Push Backend Image
    runs-on: ubuntu-latest

    # Run ONLY if backend folder changed
    if: contains(join(github.event.commits.*.modified), 'backend/')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dquiz-backend-1:latest ./backend

      - name: Push backend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dquiz-backend-1:latest


  build-frontend:
    name: Build & Push Frontend Image
    runs-on: ubuntu-latest

    # Run ONLY if frontend folder changed
    if: contains(join(github.event.commits.*.modified), 'frontend/')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dquiz-frontend-1:latest ./frontend

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dquiz-frontend-1:latest
