name: DQuiz CI/CD Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      backend_changed: ${{ steps.filter.outputs.backend }}
      VERSION: v41
    steps:
      - uses: actions/checkout@v4

      - name: Detect changed directories
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - "frontend/**"
            backend:
              - "backend/**"

  build-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" |
             docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" |
             docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build + Push Frontend (Hub + GHCR)
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          VERSION=v41

          # build with NEW IMAGE NAME
          docker build -t deviliam/dquiz-frontend-1:${VERSION} \
                       -t deviliam/dquiz-frontend-1:sha-${SHORT_SHA} \
                       -t deviliam/dquiz-frontend-1:latest ./frontend

          # push to DockerHub
          docker push deviliam/dquiz-frontend-1:${VERSION}
          docker push deviliam/dquiz-frontend-1:sha-${SHORT_SHA}
          docker push deviliam/dquiz-frontend-1:latest

          # tag for GHCR
          docker tag deviliam/dquiz-frontend-1:${VERSION} ghcr.io/devendra-5470/dquiz-frontend-1:${VERSION}
          docker tag deviliam/dquiz-frontend-1:sha-${SHORT_SHA} ghcr.io/devendra-5470/dquiz-frontend-1:sha-${SHORT_SHA}
          docker tag deviliam/dquiz-frontend-1:latest ghcr.io/devendra-5470/dquiz-frontend-1:latest

          # push to GHCR
          docker push ghcr.io/devendra-5470/dquiz-frontend-1:${VERSION}
          docker push ghcr.io/devendra-5470/dquiz-frontend-1:sha-${SHORT_SHA}
          docker push ghcr.io/devendra-5470/dquiz-frontend-1:latest


  build-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" |
             docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" |
             docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build + Push Backend (Hub + GHCR)
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          VERSION=v41

          # build with NEW IMAGE NAME
          docker build -t deviliam/dquiz-backend-1:${VERSION} \
                       -t deviliam/dquiz-backend-1:sha-${SHORT_SHA} \
                       -t deviliam/dquiz-backend-1:latest ./backend

          # push to DockerHub
          docker push deviliam/dquiz-backend-1:${VERSION}
          docker push deviliam/dquiz-backend-1:sha-${SHORT_SHA}
          docker push deviliam/dquiz-backend-1:latest

          # tag for GHCR
          docker tag deviliam/dquiz-backend-1:${VERSION} ghcr.io/devendra-5470/dquiz-backend-1:${VERSION}
          docker tag deviliam/dquiz-backend-1:sha-${SHORT_SHA} ghcr.io/devendra-5470/dquiz-backend-1:sha-${SHORT_SHA}
          docker tag deviliam/dquiz-backend-1:latest ghcr.io/devendra-5470/dquiz-backend-1:latest

          # push to GHCR
          docker push ghcr.io/devendra-5470/dquiz-backend-1:${VERSION}
          docker push ghcr.io/devendra-5470/dquiz-backend-1:sha-${SHORT_SHA}
          docker push ghcr.io/devendra-5470/dquiz-backend-1:latest
