name: Test Secrets

on:
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Test secrets exist
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USER }}" ]; then
            echo "USER is empty"; exit 1;
          fi
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "TOKEN is empty"; exit 1;
          fi
          echo "Secrets exist."
